### ISSUE TITLE
Erro na documentação de exemplo com PHP

### ISSUE THREAD

**Issue by paulocoutinhox** [moiplabs/moip-php#20]
URL:
https://github.com/moiplabs/moip-php

Tem 2 erros no código:

1 - $moip->setValue('123456')    <- sem ponto e vírgula no final

2 - $moip->setCredencials(array('key'=>'sua_key','token'=>'seu_token'));   <- é setCredential

O mesmo para fluent interfaces.

**Comment by aleborba** [comment]
Documentação ajustada. 
Obrigado pela contribuição!
