### ISSUE TITLE
Laravel Framework

### ISSUE THREAD

**Issue by SOSTheBlack** [moiplabs/moip-php#46]
Tem algum repositorio ou está em desenvolvimento o moip adptado/compativel com o Framework Laravel4 ou 5?

**Comment by vagnerfiuza** [comment]
Jean, hoje estamos trabalhando para criar um novo SDKs para as APIs v2.0 do Moip, nesse novo podemos levantar esse possibilidade, mas não iremos incorporar esse SDK atual com novas funcionalidades, apenas manter seu estado de funcionamento.

**Comment by SOSTheBlack** [comment]
@vagnerfiuza fiquei sabendo dessa APIs v2.0 também, e que vai lançar essa ano ainda, a APIs v1.0 é de 2012... já está na hora de criar algo totalmente REST FULL ^^

Tomei a liberdade de fazer um packge para o Laravel da APIs v1.0

https://github.com/SOSTheBlack/moip
