### ISSUE TITLE
Checkout sem a etapa Javascript

### ISSUE THREAD

**Issue by lucaswxp** [moiplabs/moip-php#49]
Boa noite, pessoal.

Ontem publiquei uma "adição" às funcionalidade do Moip PHP em que possibilitará o usuário pegar o token e finalizar o pagamento sem sair do servidor: https://github.com/lucaswxp/moip-checkout-transparente-sem-javascript

Só queria que soubessem da existência dessa classe e que seria uma honra se incorporassem à API atual :) (se for o caso, obviamente com algumas melhorias)

Abs

**Comment by pedrorocha-net** [comment]
Lucas, acredito que o ponto todo é que o Checkout Transparente tem como objetivo justamente que os dados do pagamento nunca passem pelo seu servidor, garantindo a segurança no tráfego entre Moip e cliente diretamente e permitindo que você não precise se preocupar com SSL, entre outras medidas de segurança.

Não digo nem que eu concorde ou discorde, apenas é o propósito da API mesmo. Eu implementei para o CMS Drupal essa integração(http://drupal.org/project/moip), tanto em PHP como JS.

Obs: concordo com você que a API deles poderia ser mais completa e permitir isso também, pois muitos projetos podem se utilizar disso(aqueles que já cuidam da segurança por sí próprios).

**Comment by lucaswxp** [comment]
Entendo @pedrorocha-net, não tinha pensado nisso.

Bom para meus projetos com Moip, sempre temos SSL habilitado, por projetar mais confiança.... mas finalmente entendi o porquê da API Javascript ;)
